version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  database:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge